"" Vim config
""
""
"" Symbolic link
"" ln -s ~/github/dotfiles/vim/vimrc ~/.vimrc
""
"" Use plug to install vim plugins
"" :PlugInstall
""
"" Manually install vim plug
"" $ curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

"" Plug START
call plug#begin()
Plug 'morhetz/gruvbox'
call plug#end()
"" Plug END


"" Syntax highlighting
syntax on

"" Tabs
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

"" Hide vsplit border
highlight VertSplit cterm=NONE
set fillchars+=vert:\ 

"" Key mappings
let mapleader = "\<Space>"
map <leader>h <C-w>h
map <leader>j <C-w>j
map <leader>k <C-w>k
map <leader>l <C-w>l
map <leader># :set number!<CR> "" toggle line numbers

"" Set theme
set background=dark
colorscheme gruvbox
